// <auto-generated />
using DuDatabase.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace DuDatabase.Migrations
{
    [DbContext(typeof(DeltaUpsilonContext))]
    partial class DeltaUpsilonContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DuDatabase.Models.Committee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("Budget");

                    b.Property<string>("Name");

                    b.Property<int>("TransactionId");

                    b.HasKey("Id");

                    b.ToTable("Committees");
                });

            modelBuilder.Entity("DuDatabase.Models.CommitteehasMembers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CommitteeId");

                    b.Property<int>("MemberId");

                    b.HasKey("Id");

                    b.HasIndex("CommitteeId");

                    b.HasIndex("MemberId");

                    b.ToTable("CommitteeMembers");
                });

            modelBuilder.Entity("DuDatabase.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("Amount");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<float>("Fundraising");

                    b.Property<string>("LastName");

                    b.Property<string>("PaymentPlan");

                    b.Property<string>("PhoneNumber");

                    b.Property<float>("ServiceHours");

                    b.HasKey("Id");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("DuDatabase.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("AmountAdded");

                    b.Property<float>("AmountSpent");

                    b.Property<int?>("CommitteeId");

                    b.HasKey("Id");

                    b.HasIndex("CommitteeId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("DuDatabase.Models.CommitteehasMembers", b =>
                {
                    b.HasOne("DuDatabase.Models.Committee", "Committee")
                        .WithMany("CommitteeMembers")
                        .HasForeignKey("CommitteeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DuDatabase.Models.Member", "Member")
                        .WithMany("CommitteeMembers")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DuDatabase.Models.Transaction", b =>
                {
                    b.HasOne("DuDatabase.Models.Committee", "Committee")
                        .WithMany("Transactions")
                        .HasForeignKey("CommitteeId");
                });
#pragma warning restore 612, 618
        }
    }
}
